### PR TITLE
Issues with typescript templates when testing the integration into SAP Fiori tools in BAS

### PR DESCRIPTION
**Pull request by tobiasqueck**
Issues internally reported by @IainSAP 

* Generation of FEOP template contained a `Component.js` but not `Component.ts` even if `typescript: true` (reproducible in VSCode as well)
    * fix: https://github.com/SAP/open-ux-tools/pull/669/commits/a2d7a24ce20e38b2119756353f2107f00245c3a3
* Generation of FPM template contained both a `Component.js` and a `Component.ts` when `typescript: true`
    *  https://github.com/SAP/open-ux-tools/pull/669/commits/7adab76707f73cdba0f0a1c7b45ac18f1e189890 might be the fix 
    * https://github.com/SAP/open-ux-tools/pull/669/commits/64c2a891564c052cbd9156232f51db0df15b9300 might be the fix (a similar fix was required for easy-ui5)
* `flpSandbox.html` was broken if the option reuselibs was set to false
   * fixed with https://github.com/SAP/open-ux-tools/commit/6153c5cdf7a3c67db2b2231027cbc4acc3df02d4  
* when using the FPM template with typescript the controller was generated as js but the component as ts file
   * https://github.com/SAP/open-ux-tools/pull/669/commits/c4c047f76d4f07e72ec5fbb708e77c7cdf785054

To better debug this issue and similar issues in the future, I have also enhanced the simple generator example with https://github.com/SAP/open-ux-tools/pull/669/commits/1da52259738ecd8ae82f9fbb3fd8f4a8c94deee4. Leading to an API relaxation for the `createForDestination` function to make it better usable (https://github.com/SAP/open-ux-tools/pull/669/commits/e9c57d9de81a0789fd34c0d991e883d2308b29dd).

To manually debug the issue, checkout this branch and run `pnpm install && pnpm build` in the root and then go to the `examples/simple-generator` project and run `pnpm start --typescript` and enter a valid v4 service and pick FPM.

### CODE REVIEW

**Comment by devinea** [comment]
Thanks @tobiasqueck. 
Can you get `packages/fiori-elements-writer/test/test-output/feopTemplate/fefeop2-ts` preview to load. It doesn't for me.

**Comment by tobiasqueck** [comment]
> Thanks @tobiasqueck. Can you get `packages/fiori-elements-writer/test/test-output/feopTemplate/fefeop2-ts` preview to load. It doesn't for me.

It is caused by my "favorit" the reuse libs script (again). Will fix it.

**Comment by tobiasqueck** [comment]
@devinea fixed with https://github.com/SAP/open-ux-tools/pull/669/commits/6153c5cdf7a3c67db2b2231027cbc4acc3df02d4

**Review by devinea — APPROVED** [review]
Thanks for the update. Tested locally and preview for FEOP works with TS now.

**Review by IainSAP — APPROVED** [review]
Thx @tobiasqueck

**Review by nlunets — APPROVED** [review]

**Pull request merged**
