### PR TITLE
fix(backend-proxy-middleware): support direct OData service url in BAS

### PR DESCRIPTION
**Pull request by zdravko-georgiev**
Fixes https://github.com/SAP/open-ux-tools/issues/575

### CODE REVIEW

**Review by Klaus-Keller — APPROVED** [review]
- Code looks good
- Unit test coverage is added
Approved

**Review by Klaus-Keller — APPROVED** [review]
Thanks for fixing the code smell

**Review by devinea — APPROVED** [review]
Thanks @zdravko-georgiev 
Changes and tests look good.

**Comment by tobiasqueck** [comment]
@zdravko-georgiev while your PR fixes the problem, it is from a typing perspective incorrect what you did. Could you do me a favor and add another correction?

The problem that you uncovered is that the type `DestinationBackendConfig` was incorrectly defined, it should have contained the optional `url` parameter. Once you correct that, you can remove the incorrect type assignment in https://github.com/SAP/open-ux-tools/blob/main/packages/backend-proxy-middleware/src/base/proxy.ts#L290-L291 and just do `proxyOptions.target = backend.url;`.

Technically it doesn't make a difference for fixing this issue but it corrects the type, hopefully helping to prevent and uncover similar issues in the future.

**Comment by zdravko-georgiev** [comment]
Thanks for reviewing @tobiasqueck, will prepare a PR with the correction.

**Pull request merged**
