### PR TITLE
Invalid target aggregation and index are accepted in Add Fragment dialog

### PR DESCRIPTION
**Pull request by nikmace**
Fix for #1513.

- Changes ComboBox to Select control.

### CODE REVIEW

**Comment by nikmace** [comment]
@zdravko-georgiev The newly created PR still has the problem with CLA..

**Review by GDamyanov — APPROVED** [review]
Small and simple change
Code looks good
Manual testing done

**Review by zdravko-georgiev — APPROVED** [review]
Code looks good
Excellent test coverage
Did NOT tested manually

**Comment by zdravko-georgiev** [comment]
@nikmace This commit is causing the CLA check to fail. If you create a new branch and cherry-pick all commits, but this one. The CLA check will pass. You can omit also the merge commits 😉 
image

**Pull request merged**
