### PR TITLE
fix: add description in i18n.properties

### PR DESCRIPTION
**Pull request by GDamyanov**
fix for: #2084 

- Add description in i18n.properties

### CODE REVIEW

**Review by nikmace — DISMISSED** [review]
Change looks straightforward
Did not test manually

**Review by voicis — CHANGES_REQUESTED** [review]
I don't see any test changes so it looks like the new code isn't tested. Please add a test for this.

**Review by voicis — DISMISSED** [review]
- Straight forward change
- Review comments addressed
- Changeset present
- Good test coverage
- Did not test manually

**Review by mmilko01 — DISMISSED** [review]
- Straight forward change
- Good test coverage
- Did not test manually

**Review by voicis — APPROVED** [review]

**Pull request merged**
