### PR TITLE
fix: inital comments and fixes

### PR DESCRIPTION
**Pull request by johannes-kolbe**
Draft PR for #2371 for testing/consumption

### CODE REVIEW

**Comment by johannes-kolbe** [comment]
Hi @broksy please feel free to create your own PR with the changes. This was just to initially add the changes.

Feedback from testing and consuming on tools-suite side:
- [x] `ui5-mock.yaml` services seems ok now with fix
  - [ ] `metadataPath` and `mockdataPath` should not be created
- [ ] `ui5-local.yaml` still gets several `sap-fe-mockserver` created
- [ ] `ui5.yaml` if two different systems are used for creation, currently syntax is wrong
    ```
        backend:
          - - path: /sap
              url: https://...
            - path: /sap
              url: https://...
              client: '000'
    ```  
- [ ] `manifest.json` creation with 2 systems not correct

Will extend the symptoms with further testing. Also not sure which parts are open-source related and which from consumer side

**Comment by johannes-kolbe** [comment]
@broksy This PR can be closed, correct?

**Comment by broksy** [comment]
> @broksy This PR can be closed, correct?

Yes. This https://github.com/SAP/open-ux-tools/pull/2499 is the actual one for https://github.com/SAP/open-ux-tools/issues/2371.

**Comment by johannes-kolbe** [comment]
Closing PR in favour of #2499

**Pull request closed without merging**
