### PR TITLE
Upgrading `rimraf` to remove problematic dependency to `minimatch`

### PR DESCRIPTION
**Pull request by tobiasqueck**
Required for #1751

I did not add a changeset on purpose because the change does not affect anything we release.

### CODE REVIEW

**Review by Klaus-Keller — APPROVED** [review]
Version bump looks good, thanks @tobiasqueck.

**Review by Klaus-Keller — APPROVED** [review]
Version bump and adjustments look good, approved.

**Review by devinea — APPROVED** [review]
rimraf update looks good.
I guess there will more PR's needed to full upgrade minimatch

**Review by voicis — APPROVED** [review]
- `rimraf` update looks good
- Changes to `clean` scripts look good
- Tested that the `clean` scripts work as expected

**Review by zdravko-georgiev — APPROVED** [review]
Package update looks good
Local `build` and `clean` worked

**Pull request merged**
