### PR TITLE
feat(jest-file-matchers): adds new module `sap-ux/jest-file-matchers`

### PR DESCRIPTION
**Pull request by cianmSAP**
#1617

Adds new module with custom file matchers for jest

### CODE REVIEW

**Review by IainSAP — APPROVED** [review]
Thanks @cianmSAP 

- Good test coverage
- Good tsdocs
- It has been indicated that consumption has been tested internally

**Review by devinea — APPROVED** [review]
Thanks @cianmSAP 
New module set-up ✅ 
readme ✅ 
changeset ✅ 
Sonar config ✅ 
Good test coverage ✅

**Review by Klaus-Keller — CHANGES_REQUESTED** [review]
Can we have a look at the cognitive complexity issues: https://sonarcloud.io/project/issues?id=SAP_open-ux-tools&pullRequest=1626&resolved=false&inNewCodePeriod=true

Once that is in `main` branch, usually no one is taking care of it anymore.

**Review by Klaus-Keller — APPROVED** [review]
Thanks @cianmSAP, looks good!
- Code is easy to understand
- Test coverage is ok
- Did locally build and run unit tests

Approved from my side.

**Review by devinea — APPROVED** [review]
Updates lg. Re-approving.

**Pull request merged**
