### PR TITLE
Fix(fpm-writer): change building block required library to sap.fe.core

### PR DESCRIPTION
**Pull request by AlinaGovoruhina**
Issue #2241 

When adding a building block validate minimum required `sap.fe.core` library in manifest.json, not `sap.fe.templates`.

### CODE REVIEW

**Review by 815are — COMMENTED** [review]
I think we should rename test `'validate sap.fe.templates manifest dependency'`?
https://github.com/SAP/open-ux-tools/blob/fix/building-block-required-library/packages/fe-fpm-writer/test/unit/building-block.test.ts#L75

**Comment by AlinaGovoruhina** [comment]
> I think we should rename test `'validate sap.fe.templates manifest dependency'`? https://github.com/SAP/open-ux-tools/blob/fix/building-block-required-library/packages/fe-fpm-writer/test/unit/building-block.test.ts#L75

Thanks, updated that

**Review by 815are — APPROVED** [review]
checked:
1. code easy to understand and does not provide regression
2. test project adjusted to fulfil new expectation
3. changeset persists

**Review by devinea — APPROVED** [review]
Changes look good. 
I assume there is no need to accept `sap.fe.templates` as fallback if `sap.fe.core` is missing.

**Pull request merged**
