### PR TITLE
Tbi/app gen/session storage connector 23289

### PR DESCRIPTION
**Pull request by unseen1980**
https://github.com/SAP/open-ux-tools/issues/1158

### CODE REVIEW

**Comment by zdravko-georgiev** [comment]
> @unseen1980 Can you address [#1158 (comment)](https://github.com/SAP/open-ux-tools/issues/1158#issuecomment-1671160488) ?

@devinea This needs to be checked first. For now we will only add the session storage connector in the generators.

**Review by zdravko-georgiev — APPROVED** [review]
Code change is simple and easy to understand
Excellent code coverage

**Review by devinea — APPROVED** [review]
Thanks for the update @unseen1980

**Comment by unseen1980** [comment]
Thank you all 👍

**Pull request merged**
