### PR TITLE
feat: add namespaces to annotation template

### PR DESCRIPTION
**Pull request by mmilko01**
#2549

- Extends current Annotation XML template
- Enhances `@sap-ux/adp-tooling` to fetch $metadata for a given Data Source
- Extends `@sap-ux/adp-tooling` writing logic to render the new template
- Consumes the new functionality on `sap-ux add annotations` CLI implementation
- Extends the `sap-ux add annotations` to be based on the merged descriptor and not the base descriptor

### CODE REVIEW

**Review by Jimmy-Joseph19 — APPROVED** [review]

**Review by Jimmy-Joseph19 — COMMENTED** [review]
Changes looks good. Annotation file are written with namespace and alias

**Review by Jimmy-Joseph19 — APPROVED** [review]
Reviewed changes in adp-tooling and create package
Changes looks good for fetching metadata and finding namespace
Tested with app in playground - Generated annotation file is now compliant and can annotate targes.
Test coverage good.

Need to align
Whether subfolder in changes folder required for annotation change?

**Review by devinea — APPROVED** [review]
Reviewed changes to `odata-service-writer`. 
This looks fine. Thanks.
Changset ✅

**Review by testojs — APPROVED** [review]
* code looks good
* great coverage
* not tested manually

**Comment by mmilko01** [comment]
@Jimmy-Joseph19 as we discussed, the change of the subfolder containing manifest changes from `/manifest` to `/changes` will be done as part of a new PR for all generators.

**Review by Klaus-Keller — APPROVED** [review]
Thanks @mmilko01,
* focused my review on create module, changes look good
* changeset exists
* test coverage is great
* did a visual review, no manual test

Approvde from my side.

**Pull request merged**
