### PR TITLE
fix(sonar): promises should not be misused

### PR DESCRIPTION
**Pull request by kranthie-sap**
# Issue

#1159

Sonar Qube bugs:
1. Promise returned in function argument where a void return was expected.
Promises should not be misused [typescript:S6544](https://sonarcloud.io/organizations/sap-1/rules?open=typescript%3AS6544&rule_key=typescript%3AS6544)
`packages/.../src/components/UITable/UITable-helper.tsx`
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AYfrPj_2SN0lrgwATVOw

2. Promise-returning function provided to property where a void return was expected.
Promises should not be misused [typescript:S6544](https://sonarcloud.io/organizations/sap-1/rules?open=typescript%3AS6544&rule_key=typescript%3AS6544)
`packages/ui5-proxy-middleware/src/ui5/middleware.ts`
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AYfrPkWISN0lrgwATVQm

# Description
* Update sources to fix errors
* Add `eslint` rule `"@typescript-eslint/no-misused-promises"` to prevent future occurrences, but it doesn't seem to cover all cases from sonar cloud

### CODE REVIEW

**Review by zdravko-georgiev — COMMENTED** [review]
Hi @kranthie-sap, thanks for fixing. I updated the unit test. One question, shouldn't we add a changeset?

**Comment by kranthie-sap** [comment]
@zdravko-georgiev: Thanks for updating the unit test. I will add a changeset when I figure out the eslint rule to use to prevent such errors.

**Review by Klaus-Keller — DISMISSED** [review]
Thanks @kranthie-sap 
- sonar fixes look good
- focused review on ui-components
- did not test locally

Approved from my side

**Review by Klaus-Keller — APPROVED** [review]
Reviewed again, added lint rule looks good.

**Review by devinea — APPROVED** [review]
code changes, eslint config, changeset and test upload look good.

**Pull request merged**
