### PR TITLE
fix(ui5-application-writer): Fixes ui5.package defaults merging

### PR DESCRIPTION
**Pull request by IainSAP**
Fixes https://github.com/SAP/open-ux-tools/issues/345

### CODE REVIEW

**Review by Klaus-Keller — APPROVED** [review]
Code looks good, I've checked out the branch and debugged through the test.

**Review by devinea — APPROVED** [review]
Changes lg. Would be good to have tests where the passed in devDep, scripts overlap with the defaults, but maybe a different version number for example.

**Review by zdravko-georgiev — APPROVED** [review]

**Comment by IainSAP** [comment]
> Changes lg. Would be good to have tests where the passed in devDep, scripts overlap with the defaults, but maybe a different version number for example.

For sure, will add additional test in the `fiori-elements-writer` PR https://github.com/SAP/open-ux-tools/pull/339 which needs to consume this fix anyway.

**Comment by IainSAP** [comment]
Thx for the timely reviews @devinea @Klaus-Keller @zdravko-georgiev .

**Pull request merged**
