### PR TITLE
Removing obsolete overrides

### PR DESCRIPTION
**Pull request by tobiasqueck**
None of the previous overrides is still required since none of our dependencies has a nested dependency to a vulnerable version.

Validated by running `pnpm audit` and by manually checking the `pnpm-lock.yaml` for any references to vulnerable versions.

### CODE REVIEW

**Review by zdravko-georgiev — DISMISSED** [review]

**Review by zdravko-georgiev — APPROVED** [review]

**Review by zdravko-georgiev — APPROVED** [review]

**Review by kranthie-sap — DISMISSED** [review]
Looks good to me. It's great to have an empty overrides section. Thanks, Tobias.

**Review by donal-tobin-sap — CHANGES_REQUESTED** [review]
The others are fine.
But vm2 should be 3.9.11 now.

**Comment by tobiasqueck** [comment]
> The others are fine. But vm2 should be 3.9.11 now.

I am not sure I understand. Do you have a link to the vulnerability that conflicts with any version in our lockfile?

**Comment by tobiasqueck** [comment]
@donal-tobin-sap thanks! Please re-review.

**Review by kranthie-sap — APPROVED** [review]

**Review by donal-tobin-sap — APPROVED** [review]

**Pull request merged**
