### PR TITLE
docs(jsdoc): add to various models.js

### PR DESCRIPTION
**Pull request by vobu**
This PR adds JSDoc to the following files:
- packages/fiori-freestyle-writer/templates/basic/add/webapp/model/models.js
- packages/fiori-freestyle-writer/templates/listdetail/add/webapp/model/models.js
- /packages/fiori-freestyle-writer/templates/worklist/add/webapp/model/models.js

Rationale behind this is the integration of `prettier` in `easy-ui5` and at the same time the reuse of the open-ux app templates in `easy-ui5`:
we discovered the `prettier`-style `lint` task in `easy-ui5` failing b/c of missing JSDoc in the above files - see the thread from this comment on https://github.com/ui5-community/generator-ui5-project/issues/26#issuecomment-1007258770

so for the time being we added `models.js` to the `.prettierignore` in `easy-ui5` - something we'd prefer not to do of course; and that we can revert after valid JSDoc is added to the above files.

### CODE REVIEW

**Comment by tobiasqueck** [comment]
@vobu thanks a lot for the PR. Could you please run `pnpm changeset` in the root of the repo to generate a changeset config containing a patch for `fiori-freestyle-writer`

PS: looking at you change, I have noticed that all three templates contain the exact same file for the model, therefore, if you like, you can also copy one of them into `./templates/common/add/webapp/model` and delete the others. If not, then I will take care of it later.

**Comment by vobu** [comment]
> @vobu thanks a lot for the PR. Could you please run `pnpm changeset` in the root of the repo to generate a changeset config containing a patch for `fiori-freestyle-writer`

done. also committed the resulting .md file - hopefully this is the intended workflow? (i don't know what i'm doing when it comes to changesets)

> PS: looking at you change, I have noticed that all three templates contain the exact same file for the model, therefore, if you like, you can also copy one of them into `./templates/common/add/webapp/model` and delete the others. If not, then I will take care of it later (in another PR).

done

**Comment by vobu** [comment]
help-welp: how do you update the `jest` snapshots manually? couldn't find any `npm` script tasks pointing to that

**Comment by tobiasqueck** [comment]
> hopefully this is the intended workflow

Yes, you did everything correctly. Once your change is merged, our pipeline will kick-in and update the version in the `package.json`, remove the md file, and push to npmjs.

**Comment by tobiasqueck** [comment]
> how do you update the jest snapshots manually

In the project you want to update the snapshots execute `pnpm test -- -u`

**Review by tobiasqueck — APPROVED** [review]
- [x] changes look good, quality of generated files is improved
- [x] snapshots correctly updated, and tests passed 
- [x] correct changeset included

**Comment by devinea** [comment]
@vobu  I suppose this supersedes https://github.com/SAP/open-ux-tools/pull/261 as resolving 
Do you need the changes in `Component.js` as mentioned in https://github.com/SAP/open-ux-tools/issues 254?
 
FYI @ciaradaly2021

**Review by devinea — APPROVED** [review]

**Comment by vobu** [comment]
> @vobu I suppose this supersedes #261 as resolving #254 Do you need the changes in `Component.js` as mentioned in #261?

yeah, that would be good. thx!

**Pull request merged**
