### PR TITLE
FEAT - Add @sap-ux/nodejs-utils module

### PR DESCRIPTION
**Pull request by devinea**
FEAT - Add @sap-ux/nodejs-utils module
Includes wrapper functions for nodejs provided API's e.g. spawn
replacement for part of common-utils

### CODE REVIEW

**Review by cianmSAP — APPROVED** [review]
New module looks good
Tests to cover
Have not tested 
Changeset ✅

**Review by donal-tobin-sap — APPROVED** [review]
Module addition looks fine to me.

**Review by longieirl — APPROVED** [review]
Changes look good.
Test coverage is good.

**Comment by devinea** [comment]
Thanks all

**Pull request merged**
