### PR TITLE
Same license reference in all modules

### PR DESCRIPTION
**Pull request by tobiasqueck**
The PR consolidates the usage of "Apache-2.0" as license reference in all `package.json` files instead of using "SEE LICENSE IN LICENSE".

This is **NOT** a change of the license because the `LICENSE` file included in all modules is the Apache 2.0 license, this is just a change of the reference in the `package.json` to be consistent.

I don't think this needs to be released but can simply get out with the next change of the affected modules, therefore, I didn't add a changeset.

### CODE REVIEW

**Review by devinea — COMMENTED** [review]
Added some more changes to be consistent in all modules. 
Maybe best to add a patch Changeset so that the modules on npmjs show the correct license.
https://www.npmjs.com/package/@sap-ux/store

**Review by devinea — APPROVED** [review]
Changeset and updates look good now. 
thanks

**Comment by tobiasqueck** [comment]
@zdravko-georgiev any chance you could review as well?

**Review by zdravko-georgiev — APPROVED** [review]
License changes looks good

**Pull request merged**
