### PR TITLE
fix(preview-middleware): do not block app loading if registering of reuse libs fails

### PR DESCRIPTION
**Pull request by zdravko-georgiev**
Follow-up of https://github.com/SAP/open-ux-tools/issues/1557.

If for some reason the registering of the reuse libs fails, then the application should not be blocked from loading.

### CODE REVIEW

**Review by Klaus-Keller — APPROVED** [review]
Thanks @zdravko-georgiev for improving the error handling.
- Code looks good
- Test coverage is great
- Did no manual test

Approved from my side

**Review by johannes-kolbe — APPROVED** [review]
- code changes lgtm
- test provided
- changeset provided
- did not test manually

**Review by 815are — APPROVED** [review]
Checked:
1. code changes easy to read
2. test case with error simulation is added
3. did not test manually

**Comment by zdravko-georgiev** [comment]
Thanks guys!

**Pull request merged**
