### PR TITLE
Use  @sap-ux/eslint-plugin-fiori-tools for JS projects

### PR DESCRIPTION
**Pull request by devinea**
https://github.com/SAP/open-ux-tools/issues/983

Use @sap-ux/eslint-plugin-fiori-tools for JS projects

### CODE REVIEW

**Review by tobiasqueck — APPROVED** [review]
* changes are fine
* changeset is ok (I approved) BUT it would be better to actually split it in two
   * eslint: the one you have
   * ui5-app-writer: fixing the incorrectly used export for ts and enabling it for js

**Review by tobiasqueck — APPROVED** [review]
* changes are fine
* changeset is ok (I approved) BUT it would be better to actually split it in two
   * eslint: the one you have
   * ui5-app-writer: fixing the incorrectly used export for ts and enabling it for js

**Review by IainSAP — APPROVED** [review]
LGTM

- Updated as expected

**Comment by devinea** [comment]
Thanks @tobiasqueck @IainSAP

**Pull request merged**
