### PR TITLE
fix(ui-components): update dependencies

### PR DESCRIPTION
**Pull request by Klaus-Keller**
Issue: https://github.com/SAP/open-ux-tools/issues/780

### CODE REVIEW

**Review by tobiasqueck — APPROVED** [review]
version updates, resolutions and resulting changes to the `pnpm-lock.yaml` look as expected.
I did not check if these changes have an impact on the `ui-components` functionality.

**Review by tobiasqueck — APPROVED** [review]

**Review by devinea — APPROVED** [review]
That is a lot of updates. Tools-suite would be best to get the same updates when consuming UI components.
Quick check on storybook locally looks OK.

**Comment by Klaus-Keller** [comment]
> That is a lot of updates. Tools-suite would be best to get the same updates when consuming UI components. Quick check on storybook locally looks OK.

@devinea my bad. I've also asked @815are to double check consumption.

**Review by 815are — APPROVED** [review]
As tested works ok for me,

only faced one build error in consumption:
image
but it is adjustable
otherwise my tests were ok

**Pull request merged**
