### PR TITLE
fix(@sap-ux/odata-service-inquirer): #2621 Adds system prompt breadcrumb

### PR DESCRIPTION
**Pull request by IainSAP**
Fix for #2621 

- Updates service type warning text
- Adds breadcrumb to system prompt
- Adds hint to system prompt

### CODE REVIEW

**Review by longieirl — DISMISSED** [review]
Changes look good.
Text changes are good.
Texts are updated.

**Review by cianmSAP — CHANGES_REQUESTED** [review]
Actually, there are two changesets

**Review by cianmSAP — DISMISSED** [review]

**Review by cianmSAP — APPROVED** [review]
Re-approving

**Review by longieirl — APPROVED** [review]
Re-approving

**Pull request merged**
