### PR TITLE
Enhancing contribution guidelines

### PR DESCRIPTION
**Pull request by tobiasqueck**
* added guidance for reviews

### CODE REVIEW

**Review by Klaus-Keller — DISMISSED** [review]
Thanks @tobiasqueck for adding clarifications on reviews.
I read through them and agree, approved from my side.

**Review by devinea — APPROVED** [review]

**Review by devinea — DISMISSED** [review]
Seems like a practical approach

**Review by Klaus-Keller — APPROVED** [review]
Also checked the newly added guideline for: "one issue per PR".
Makes sense to me, approved.

**Review by IainSAP — APPROVED** [review]
Thx.

**Pull request merged**
