### PR TITLE
feat(project-access): expose "toReferenceUri" in package interface

### PR DESCRIPTION
**Pull request by UweSchwerk**
needed for calculating `using` statements during cds code generation (part of new package "fiori-annotation-api")

### CODE REVIEW

**Review by Klaus-Keller — APPROVED** [review]
Exporting `toReferenceUri` is fine, approved

**Review by voicis — CHANGES_REQUESTED** [review]
It still isn't exposed on package level. Changes in `src/index.ts` are also needed.

**Comment by UweSchwerk** [comment]
> It still isn't exposed on package level. Changes in `src/index.ts` are also needed.

My bad - yes. Corrected

**Review by voicis — DISMISSED** [review]
- simple change exposing `toReferenceUri`
- review comments addressed
- tested locally

**Review by Klaus-Keller — CHANGES_REQUESTED** [review]
Hi @UweSchwerk,

Can we also change the import in the test to reflect that it should be exported from top level here:
https://github.com/SAP/open-ux-tools/blob/938989688353d1d29140b8cf59ad8aa59d447fb2/packages/project-access/test/project/cap.test.ts#L18

Just move `toReferenceUri` it to the `import {...} from '../../src';`

**Comment by UweSchwerk** [comment]
> Hi @UweSchwerk,
> 
> Can we also change the import in the test to reflect that it should be exported from top level here:
> 
> https://github.com/SAP/open-ux-tools/blob/938989688353d1d29140b8cf59ad8aa59d447fb2/packages/project-access/test/project/cap.test.ts#L18
> 
> Just move `toReferenceUri` it to the `import {...} from '../../src';`

Done

**Review by voicis — APPROVED** [review]

**Review by Klaus-Keller — APPROVED** [review]
re-approve after exposing it on root `index.ts`

**Pull request merged**
