### PR TITLE
Update Icons.tsx

### PR DESCRIPTION
**Pull request by aislingnoone**
Update to "Info" icon

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
Hi @aislingnoone, 

Could add some information this change, is there a related ticket, where is it coming from, perhaps also a screenshot on how the new icon looks?

I think that would help the @SAP/ux-tools-ui-components team to review.

**Comment by aislingnoone** [comment]
> Hi @aislingnoone,
> 
> Could you please add some information about this change, is there a related ticket or discussion? where is it coming from? Perhaps also a screenshot on how the new icon looks?
> 
> I think that would help the @SAP/ux-tools-ui-components team to review.

Hi @Klaus-Keller 

There is no ticket on this change as it is a minor change from the design side. The icon will have a wider surface area, as this is a clickable element this is better from an accessibility perspective. This change also came about because of a visual design issue we have in one of the tools, specifically guided development, where we have this icon and another element beside each other. The new icon will enhance the visual design in this context.

image


image

Any questions feel free to ping me!

**Comment by Klaus-Keller** [comment]
Hi @aislingnoone, 
Thanks, that helps a lot! Some remarks:

1. There are some linting/format issues in your changes, see https://github.com/SAP/open-ux-tools/actions/runs/3339681576/jobs/5528921157#step:9:19. I could fix it, but it is on a branch in your fork, so I'm a bit hesitant
2. You'll need to add a changest in order to create a new version of `@sap-ux/ui-components` using command `pnpm changeset`. I think this change should just increase the patch level, for details see: https://github.com/SAP/open-ux-tools#create-changesets-for-feature-or-bug-fix-branches

Let me know if you need further help.

**Comment by devinea** [comment]
This PR can be closed as it is replaced by https://github.com/SAP/open-ux-tools/pull/766

**Pull request closed without merging**
