### PR TITLE
Tbi/app gen/local storage connector 23289

### PR DESCRIPTION
**Pull request by unseen1980**
https://github.com/SAP/open-ux-tools/issues/1158

Flexibility colleagues adviced that the SessionStorageConnector is the wrong connector. We should use LocalStorageConnector. This PR replaces SessionStorageConnector with LocalStorageConnector

### CODE REVIEW

**Review by zdravko-georgiev — APPROVED** [review]
Thanks @unseen1980

**Comment by zdravko-georgiev** [comment]
Why the 2 changesets?

**Review by tobiasqueck — CHANGES_REQUESTED** [review]
Please fix the changesets

**Comment by unseen1980** [comment]
@zdravko-georgiev @tobiasqueck I removed the second changeset. Leftover from previous PR, apologies.

**Review by zdravko-georgiev — APPROVED** [review]

**Review by tobiasqueck — APPROVED** [review]
* changeset ok
* changes look good
* did not test locally

**Comment by unseen1980** [comment]
Thank you all 👍

**Pull request merged**
