### PR TITLE
Drop Node 16 and Support Node 18 and 20

### PR DESCRIPTION
**Pull request by devinea**
https://github.com/SAP/open-ux-tools/issues/1358

-[ ] update new module after this is merged https://github.com/SAP/open-ux-tools/pull/1346

### CODE REVIEW

**Comment by donal-tobin-sap** [comment]
- note that tools-suite will not be going to node 18 until it is released to canary, the timing of which is unknown at this time

**Review by donal-tobin-sap — APPROVED** [review]
Looks good to me.
But will not be able to consume in tools-suite until tools-suite is also updated to node 18.

**Review by johannes-kolbe — DISMISSED** [review]
concise update, lgtm.
- changeset provided

**Review by zdravko-georgiev — COMMENTED** [review]
Can we please wait with this until we can switch `tools-suite` also to node 18? I need to do some fixes in the middlewares packages and will not be able to consume the fixes in `tools-suite`.

**Comment by devinea** [comment]
> Can we please wait with this until we can switch `tools-suite` also to node 18? I need to do some fixes in the middlewares packages and will not be able to consume the fixes in `tools-suite`.

@zdravko-georgiev Yes this will be coordinated with tools-suite.

**Comment by zdravko-georgiev** [comment]
> > Can we please wait with this until we can switch `tools-suite` also to node 18? I need to do some fixes in the middlewares packages and will not be able to consume the fixes in `tools-suite`.
> 
> @zdravko-georgiev Yes this will be coordinated with tools-suite.

@devinea So this PR will be only merged when also `tools-suite` is switched to node 18?

**Review by korotkovao — APPROVED** [review]
LGTM Thanks @devinea

**Review by zdravko-georgiev — APPROVED** [review]
Changes to middlewares, create and logger packages look good

**Review by tobiasqueck — APPROVED** [review]
* changesets are ok
* config changes are as expected
* did not locally test, having a successful build is sufficient for me

**Comment by tobiasqueck** [comment]
@devinea don't you need to also update our PR checks so that it is not waiting for the node 16.x builds?

**Comment by devinea** [comment]
> @devinea don't you need to also update our PR checks so that it is not waiting for the node 16.x builds?

Done.

**Pull request merged**
