### PR TITLE
chore: enable quick actions

### PR DESCRIPTION
**Pull request by voicis**
Remove feature flag check for "Add Custom Table Action", "Add Custom Page Action", "Add Custom Table Column" and "Change Table Columns" Quick Actions.

### CODE REVIEW

**Review by nikmace — DISMISSED** [review]
Changes look good
Tests adjusted and coverage is excellent
Did not test manually

**Comment by voicis** [comment]
The duplicate code check does not seem to be entirely accurate here, because it is complaining about the same variable names, even though they are imported from different files and entirely different code is referenced.

**Review by nikmace — APPROVED** [review]
Re-approving, changes look good
Coverage is 100%, although Sonar as failing (false positive)
Did not test manually

**Review by vadson71 — APPROVED** [review]
Changes are straightforward
Good test coverage 
Didn't test locally

**Pull request merged**
