### PR TITLE
chore - TS writers update to "ui5-tooling-transpile": "^0.2.1" 

### PR DESCRIPTION
**Pull request by devinea**
fix for https://github.com/SAP/open-ux-tools/issues/764 
Screenshot 2022-12-20 at 13 27 24
Screenshot 2022-12-20 at 13 27 13

### CODE REVIEW

**Review by IainSAP — COMMENTED** [review]
Thx @devinea 

-  Only version updates as expected.

**Review by cianmSAP — APPROVED** [review]

**Review by IainSAP — APPROVED** [review]

**Comment by tobiasqueck** [comment]
Hmm ... it still contains the warnings for the `-preload` files that should have been excluded by updating the `ui5*.yaml` files as recommended at https://github.com/SAP/open-ux-tools/issues/764#issuecomment-1293114225

**Comment by devinea** [comment]
> Hmm ... it still contains the warnings for the `-preload` files that should have been excluded by updating the `ui5*.yaml` files as recommended at https://github.com/SAP/open-ux-tools/issues/764#issuecomment-1293114225

I'll create a PR for that.

**Comment by devinea** [comment]
PR https://github.com/SAP/open-ux-tools/pull/850 created.

**Pull request merged**
