### PR TITLE
fix(project-access): export findCapProjectRoot

### PR DESCRIPTION
**Pull request by longieirl**
Fix for https://github.com/SAP/open-ux-tools/issues/2007

- required by new modules but doing this early so we can do some local testing

### CODE REVIEW

**Comment by longieirl** [comment]
@Klaus-Keller please review.

**Review by devinea — APPROVED** [review]
Export makes sense. 
Changset ✅

**Comment by longieirl** [comment]
Thanks @devinea this has already been previously agreed with Klaus.

**Review by kjose90 — APPROVED** [review]
Looks good.
Changeset ✅

**Pull request merged**
