### PR TITLE
https://github.com/SAP/open-ux-tools/issues/673

### PR DESCRIPTION
**Pull request by IainSAP**
Fix for: https://github.com/SAP/open-ux-tools/issues/673

### CODE REVIEW

**Review by tobiasqueck — CHANGES_REQUESTED** [review]
Could you please apply the same fix at https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/src/index.ts#L36

**Review by tobiasqueck — DISMISSED** [review]
Fix looks good, however, I don't know how to properly test it. 
Any idea how to put this in a unit test? 

If not, I am also ok with it.

**Comment by IainSAP** [comment]
> Fix looks good, however, I don't know how to properly test it. Any idea how to put this in a unit test?
> 
> If not, I am also ok with it.

Possibly by mounting the test `fs` to include a path with a dot. Will create a follow up PR if thats ok since this fix is needed as priority?

**Review by devinea — COMMENTED** [review]
@IainSAP Does this need to be applied to all `copyTpl` calls to be safe?

**Comment by IainSAP** [comment]
> @IainSAP Does this need to be applied to all `copyTpl` calls to be safe?

I dont know as that requires more extensive testing and the fix is urgent. The bug is fixed by this PR for now. A follow-up may be required with additional testing.

**Review by devinea — APPROVED** [review]
I am OK to merge this much for now.

**Comment by IainSAP** [comment]
Follow up item created: https://github.com/SAP/open-ux-tools/issues/675

**Review by tobiasqueck — APPROVED** [review]

**Pull request merged**
