### PR TITLE
Type augmentation for mem-fs-editor

### PR DESCRIPTION
**Pull request by tobiasqueck**
Proposal for discussion at https://github.com/SAP/open-ux-tools/pull/806#discussion_r1026951441.

@Klaus-Keller how about doing it like this?
@nlunets Thanks for the help!

Next steps

- [x] get opinion if this is a good option to augment types for all projects
- [x] finalize type enhancement
- [x] replace all unnecessary casts to `any`

No changeset required since it is only an internal type change.

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
@tobiasqueck, I like this proposal. Should we try to merge it separate before https://github.com/SAP/open-ux-tools/pull/806?

**Comment by tobiasqueck** [comment]
> @tobiasqueck, I like this proposal. Should we try to merge it separate before #806?

Yes, that would be my preference.

**Review by stefanschreck — APPROVED** [review]

**Review by devinea — APPROVED** [review]
Thanks @tobiasqueck 
Looks like a good approach.

**Review by Klaus-Keller — APPROVED** [review]
Adding missing type declaration in a private module makes sense to me. 
Including local type via `tsconfig.json` looks good.
I've focused review on project-access, but installed, build, and ran tests on the branch locally and it works.

**Pull request merged**
