### PR TITLE
chore: upgrade vocabularies-types + pnpm updates

### PR DESCRIPTION
**Pull request by schreckstefan**
TBI: https://github.com/SAP/open-ux-tools/issues/2529

- Upgrade of vocabularies-types  as required by CAP colleagues
- Upgrade of annotation converter
- Upgrade of other dependencies had been required by pre-commit (security, vulnerabilities)
- Corrections at fiori-annotations-api due to incompatible changes at vocabularies-types

### CODE REVIEW

**Review by devinea — DISMISSED** [review]
package updates look good. 
I didn't review annotation changes.

**Review by marufrasully — APPROVED** [review]
LGTM from annotation modeler side.

**Review by nikmace — APPROVED** [review]
Changes look good
Tests updated, coverage is excellent
Did not test manually

**Comment by voicis** [comment]
@marufrasully, @nikmace, @devinea please review again.

**Review by marufrasully — APPROVED** [review]
LGTM - annotation part only
did not test it locally.

**Review by nikmace — APPROVED** [review]
Re-approving

**Review by devinea — APPROVED** [review]
re-approving

**Pull request merged**
