### PR TITLE
fix(cf-deploy-config-writer): add runinband

### PR DESCRIPTION
**Pull request by longieirl**
- to allow tests run in sequence, there is no reason for a timeout and the timeout value is already set to 10000
- there is no time difference either in running the tests with this flag

### CODE REVIEW

**Review by cianmSAP — DISMISSED** [review]
Update for test script looks good
No changeset needed

**Review by kjose90 — DISMISSED** [review]
Thanks John - no change set required - script looks good 👍

**Review by cianmSAP — APPROVED** [review]
Re-approving

**Review by kjose90 — APPROVED** [review]
re aproving

**Pull request merged**
