### PR TITLE
fix(fpm-writer): Improve custom section fragments with event handler. Move 'core:require' attribute from inner element(Button) to wrapper(VBox)

### PR DESCRIPTION
**Pull request by 815are**
Issue #1855

Previous version generated fragment content like:
```
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m" xmlns:macros="sap.fe.macros">
	<VBox>
		<Button core:require="{ handler: 'project1/ext/fragment/Fsefsf'}" text="Fsefsf" press="handler.onPress" />
	</VBox>
</core:FragmentDefinition>
```

Then if we add new button without `core:require` then press will not work:
```
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m" xmlns:macros="sap.fe.macros">
	<VBox>
		<Button core:require="{ handler: 'project1/ext/fragment/Fsefsf'}" text="Fsefsf" press="handler.onPress" />
		<Button text="Fsefsf" press="handler.onPress" />
	</VBox>
</core:FragmentDefinition>
```

To improve usability - move `core:require` from inner element to wrapper element like:
```
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m" xmlns:macros="sap.fe.macros">
	<VBox core:require="{ handler: 'project1/ext/fragment/Fsefsf'}">
		<Button text="Fsefsf" press="handler.onPress" />
		<Button text="Fsefsf" press="handler.onPress" />
	</VBox>
</core:FragmentDefinition>
```

### CODE REVIEW

**Review by broksy — DISMISSED** [review]
Changes and changeset are clear and good test coverage.

**Review by schreckstefan — APPROVED** [review]
Code review ok.
The update snapshots show that the change meets the expectation

**Review by broksy — DISMISSED** [review]
Spacing problem is fixed including related tests.

**Review by broksy — APPROVED** [review]
Fixed snapshots.

**Review by schreckstefan — APPROVED** [review]

**Pull request merged**
