### PR TITLE
chore(open-ux-tools) ignore source map files when publishing to npm

### PR DESCRIPTION
**Pull request by devinea**
Source map files are not needed in the tgz published to npm. Removing reduces the install size.

### CODE REVIEW

**Review by zdravko-georgiev — APPROVED** [review]
Thanks Austin

**Comment by IainSAP** [comment]
@devinea This change would mean we can never debug - this does not only remove during publish. We need to still be able to generate dist/tar including source maps for debugging on BAS for example.

**Review by IainSAP — CHANGES_REQUESTED** [review]
Please check my comment and see if this is correct?

**Comment by tobiasqueck** [comment]
>  Im not suggesting we publish with source maps, but we still need a way to generate a tgz that includes them.

That sounds like a good compromise to me.

**Pull request merged**
