### PR TITLE
Improve descriptions for analytical OData annotations

### PR DESCRIPTION
**Pull request by stewsk**

### CODE REVIEW

**Comment by tobiasqueck** [comment]
@UweSchwerk @voicis could you please have a look at this proposal?

**Review by UweSchwerk — DISMISSED** [review]

**Review by tobiasqueck — CHANGES_REQUESTED** [review]
changeset is missing or should this change not trigger the release of a new version of the module?

**Review by MN-public — COMMENTED** [review]
Please add `(CDS annotation)` at the beginning of the term descriptions where missing (lines 26 and 76 in ObjectModel.ts and line 53 in ObjectModel.ts).
When used consistently, it will help the users to immediately recognize that these are not OData annotations.

**Comment by UweSchwerk** [comment]
> changeset is missing or should this change not trigger the release of a new version of the module?

@tobiasqueck Done

**Comment by UweSchwerk** [comment]
@tobiasqueck : any idea what causes the failures? I.e. git cannot checkout code...
Could it be because PR is based on forked repo ?

**Comment by tobiasqueck** [comment]
> @tobiasqueck : any idea what causes the failures? I.e. git cannot checkout code... Could it be because PR is based on forked repo ?

Yes, there still is the issue with the pipeline when running from a fork. I'd recommend that @UweSchwerk creates a new branch in the original repo, and then @stewsk creates a new PR from his branch to the new one. Then merge it and wait for the pipeline to go green in the new branch.

**Comment by UweSchwerk** [comment]
New PR: https://github.com/SAP/open-ux-tools/pull/1749

**Pull request closed without merging**
