### PR TITLE
feat(axios-extension): use token for connecting to abap cloud

### PR DESCRIPTION
**Pull request by zdravko-georgiev**
https://github.com/SAP/open-ux-tools/issues/1581. The original idea was to create a security session, but after checking with the ABAP Cloud team, it became that we do not necessarily need to create a security session. Instead we can use token for connecting.

### CODE REVIEW

**Review by cianmSAP — DISMISSED** [review]
Code updates look good
I've tested locally and deployment works as expected

**Review by cianmSAP — APPROVED** [review]
Same comments as above, improved code coverage ✅

**Review by Klaus-Keller — APPROVED** [review]

**Review by Klaus-Keller — APPROVED** [review]
Thanks @zdravko-georgiev, 
- change for sending bearer token looks good
- test coverage is good
- did not manually test it

Approved from my side.

**Comment by zdravko-georgiev** [comment]
Thanks guys!

**Pull request merged**
