### PR TITLE
fix: eslint parsing error for windows

### PR DESCRIPTION
**Pull request by tobiasqueck**
Changing all `.eslintrc` files to `.eslintrc.js` and then adding the setting `tsconfigRootDir: __dirname` to fix the reported issue on windows.

No actual code is changed, therefore, no changeset required.

Fix for #1200

### CODE REVIEW

**Review by nikmace — APPROVED** [review]
Manually tested on Windows. The problem is solved.
All is good from my side.

**Review by kranthie-sap — APPROVED** [review]
I reviewed the individual `.eslintrc.js` and the deleted `.eslintrc` files and see that the contents are copied over correctly. Changes to the tsconfig files look good too.

**Review by Klaus-Keller — APPROVED** [review]
Switch from `.eslintrc` to `.eslintrc.js` looks good. I've checked out the branch and ran `pnpm install`, `pnpm build`, `pnpm test`, and `pnpm lint` locally (Mac).
No issues found, approved from my side.

**Review by devinea — APPROVED** [review]
Updates to the writers modules look good. 
I haven't tested locally.

**Review by cianmSAP — APPROVED** [review]
Reviewed deploy-tooling, changes look good.

**Pull request merged**
