### PR TITLE
fix lint warnings in locate-reuse-libs.js

### PR DESCRIPTION
**Pull request by devinea**
follow-up fixes from https://github.com/SAP/open-ux-tools/pull/1194

### CODE REVIEW

**Review by unseen1980 — APPROVED** [review]

**Review by zdravko-georgiev — APPROVED** [review]
Reviewed `preview-middleware`:
- Change is simple as adding a semicolon at the end of the line
- Manual testing ✅

**Review by slin-sap — APPROVED** [review]
- Only change to the template file and thus the snapshots in unit tests. 
- Patch level of changeset.

**Review by Klaus-Keller — APPROVED** [review]
Lint fix to add missing `;` looks good. Did not try it locally, just visual review.

**Review by tobiasqueck — APPROVED** [review]
* both writers and preview middleware changes are as expected
* chanegset is good
* did not test it locally

**Comment by devinea** [comment]
Thanks all

**Pull request merged**
