### PR TITLE
chore: @sap-ux/create and mockserver config roundups

### PR DESCRIPTION
**Pull request by Klaus-Keller**
- Adding CODEOWNERS to `@sap-ux/create` and `@sap-ux/mockserver-config-writer` https://github.com/SAP/open-ux-tools/commit/68e7470492af175b66df1a385bca501c7d718286
- When called via `npm init @sap-ux` we see the CLI help and an error due to exit code 1. Fixed with https://github.com/SAP/open-ux-tools/commit/2728124a3bef53652b6ba31c7606afaa4b535ec8
- Text and newline correction for README file in `@sap-ux/mockserver-config-writer` https://github.com/SAP/open-ux-tools/pull/832/commits/39ab79e6e478c9cba8fe05275b0ef8ed4ed9ffa5 https://github.com/SAP/open-ux-tools/commit/65d9d1c4716f0a5a55a03aa0ca760470ef055e78

### CODE REVIEW

**Review by kranthie-sap — CHANGES_REQUESTED** [review]
Looks good to me.
GitHub reports a linting error in `CODEOWNERS` file. Have you created the `@SAP/ux-tools-create` already?

**Comment by Klaus-Keller** [comment]
> Looks good to me. GitHub reports a linting error in `CODEOWNERS` file. Have you created the `@SAP/ux-tools-create` already?

Yes, I've created the groups, but they might not have had permissions to this repo yet. I'll try to re-run the action.

**Comment by Klaus-Keller** [comment]
@kranthie-sap, I see the linting errors should be gone now

**Review by tobiasqueck — APPROVED** [review]
Thanks for the fixes. Error is gone.

**Review by devinea — APPROVED** [review]
Thanks for the updates.

**Review by kranthie-sap — APPROVED** [review]
The codeowners file seems to be fine now. The rest of the changes look good. Thanks.

**Pull request merged**
