### PR TITLE
Fix: Update popup style and labels spacing

### PR DESCRIPTION
**Pull request by emrecevik06**
Update fundamental style of popups and add more space between labels and icons
- Updated background color
- Updated border color and radius
- More spacing at labels and icons

Before: 
image
image

After:
image
image

### CODE REVIEW

**Comment by 815are** [comment]
@gpeuc @emrecevik06 

just to be sure do we need border also for following callouts?
image
image

current change only applies border color without border width and not sure if it is intended?

**Comment by gpeuc** [comment]
@815are Yep. All things that pop out should have border. 

`border: 1px solid var(--vscode-editorWidget-border);`

**Review by 815are — DISMISSED** [review]
checked:
1. change in `ui-components` is clear and fits expectation - all generic callout has border
2. tested `ui-component` update with storybook

**Review by 815are — APPROVED** [review]

**Review by vadson71 — APPROVED** [review]
Changes look good and straightforward.
Didn't test locally

**Review by vinayhospete — APPROVED** [review]

**Pull request merged**
