### PR TITLE
chore(open-ux-tools) - pnpm@7 compatibility fixes & drop node 12 and add Node 18 in pipeline

### PR DESCRIPTION
**Pull request by devinea**
Fixes due to the following changes in pnpm@7

- https://github.com/pnpm/pnpm/pull/4427
- https://github.com/pnpm/pnpm/pull/4459

Drop node 12 in the pipeline. 
Add node 18 in the pipeline.
Release is done on node 14 instead of node 12.

fixes https://github.com/SAP/open-ux-tools/issues/494

### CODE REVIEW

**Comment by devinea** [comment]
@SAP/ux-tools-admin - please review. Also can you update the the required jobs to be `18.x` instead of `12.x`

**Comment by devinea** [comment]
> @devinea: Should the engines/pnpm and engines/node settings in the package.json files also be updated?

@kranthie-sap There are updated to include pnpm@7 and Node@18 https://github.com/SAP/open-ux-tools/pull/489/files#diff-f895ef440c26485066363739138450315e1acc49099da3eb339ce9b1735a6cd8

I didn’t remove node@12 and pnpm@6 at this stage as tool-suite still uses node@12 in the build and many developers would also have node@12 locally for now. Then can be removed in a couple of months perhaps. I assume it is safe enough not to use node@12 in the pipeline as we don't change the tsconfig target for now.

**Review by kranthie-sap — DISMISSED** [review]

**Review by zdravko-georgiev — DISMISSED** [review]

**Review by tobiasqueck — APPROVED** [review]
* Tested with `pnpm` version `6.32.14` and `7.1.2` (in my new awesome Github Codespace instance) without problems.
* adding new node version support looks good as well

Out of curiosity, you updated `eslint-plugin-jsdoc`, did you have a specific reason?

**Comment by devinea** [comment]
> * Tested with `pnpm` version `6.32.14` and `7.1.2` (in my new awesome Github Codespace instance) without problems
> * adding new node version support looks good as well
> 
> Out of curiosity, you updated `eslint-plugin-jsdoc`, did you have a specific reason?

Yes the older version of `eslint-plugin-jsdoc` did not support node 18 as it specified engine in the package.json

**Review by zdravko-georgiev — APPROVED** [review]

**Pull request merged**
