### PR TITLE
Added CustomFPMPage icon

### PR DESCRIPTION
**Pull request by gpeuc**
Added CustomFPMPage icon

Screenshot 2022-10-12 at 12 29 53

### CODE REVIEW

**Review by 815are — APPROVED** [review]

**Review by 815are — DISMISSED** [review]

**Review by devinea — DISMISSED** [review]
New icon looks OK. 
No changeset included in this PR. Is that intentional?
This file is getting big. We may need to change approach soon.

**Comment by gpeuc** [comment]
> No changeset included in this PR. Is that intentional?

I have no idea what is _changeset_ 😄

**Comment by devinea** [comment]
> > No changeset included in this PR. Is that intentional?
> 
> I have no idea what is _changeset_ 😄

Details https://github.com/SAP/open-ux-tools#create-changesets-for-feature-or-bug-fix-branches
It is needed to trigger publishing a new version to npmjs when this PR is merged.

**Comment by devinea** [comment]
Changeset added in https://github.com/SAP/open-ux-tools/pull/734/commits/4c2cfa9d277abbe42043402168a307307f34b62c

**Review by devinea — APPROVED** [review]

**Comment by gpeuc** [comment]
@devinea 

To create changesets in a feature or bug fix branch, run one of the following commands:

```
pnpm cset
pnpm changeset
```

That's a negative chief, I have none of the environment installed, this is why I do edits directly in browser in GitHub.

**Review by 815are — APPROVED** [review]

**Pull request merged**
