### PR TITLE
feat: new functions for retrieving minUI5Version(s)

### PR DESCRIPTION
**Pull request by schreckstefan**
Feature request: https://github.com/SAP/open-ux-tools/issues/1988

The PR introduces the three new functions at project-access:

- getMinUI5VersionFromManifest 
- getMinUI5VersionAsArray 
- getMinimumUI5Version

### CODE REVIEW

**Review by Klaus-Keller — COMMENTED** [review]
@schreckstefan, code looks good, but I would not have it expected in `library` folder, because we have code for UI5 libraries there. Can we move it to `project` folder?
Perhaps in `packages/project-access/src/project/info.ts`?

**Comment by schreckstefan** [comment]
> @schreckstefan, code looks good, but I would not have it expected in `library` folder, because we have code for UI5 libraries there. Can we move it to `project` folder? Perhaps in `packages/project-access/src/project/info.ts`?

@Klaus-Keller 
Done, please check

**Review by Klaus-Keller — APPROVED** [review]
Thanks @schreckstefan, 
- change set exists
- code is easy to understand 
- test coverage is great
- did a local test and could not find any issues

Approved from my side

**Review by 815are — APPROVED** [review]
checked:
1. code is easy to understand;
2. tests with multiple variations are presented;
3. changelog is presented;

I did not test manually

**Pull request merged**
