### PR TITLE
chore: rm redundant lerna config file

### PR DESCRIPTION
**Pull request by ullasholla**
This PR removes the redundant `lerna.json` file. We use `pnpm` to manage our workspaces and this is a holdover from the past when `lerna` was being used.

### CODE REVIEW

**Review by kranthie-sap — APPROVED** [review]
Thanks, Ullas.

**Review by kranthie-sap — CHANGES_REQUESTED** [review]
@ullasholla: Can you also remove the references in `.gitignore` and `CODEOWNERS`, please?

**Comment by ullasholla** [comment]
@kranthie-sap:
> @ullasholla: Can you also remove the references in `.gitignore` and `CODEOWNERS`, please?

This entry in `.gitignore`?
```
lerna-debug.log*
```
I left than in because we also have a bunch of references to temp files from other tools that we don't use (grunt, istanbul, bower, etc).

Did not find anything in `CODEOWNERS`. Maybe I'm looking in the wrong place?

**Comment by kranthie-sap** [comment]
> Did not find anything in `CODEOWNERS`. Maybe I'm looking in the wrong place?

@ullasholla: It looks like the latest version of the `CODEOWNERS` has an entry for `lerna.json`.

**Review by kranthie-sap — APPROVED** [review]

**Review by donal-tobin-sap — APPROVED** [review]

**Pull request merged**
