### PR TITLE
fix(security): update webpack-dev-middleware

### PR DESCRIPTION
**Pull request by 815are**
Fix for:
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Path traversal in webpack-dev-middleware               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ webpack-dev-middleware                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=6.0.0 <6.1.2                                         │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=6.1.2                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ packages/ui-components >                               │
│                     │ @storybook/react-webpack5@7.4.3 >                      │
│                     │ @storybook/builder-webpack5@7.4.3 >                    │
│                     │ webpack-dev-middleware@6.1.1                           │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-wr3j-pwj9-hqq6      │
└─────────────────────┴────────────────────────────────────────────────────────┘
```

As I tried update of `@storybook/react-webpack5` from `7.4.3` to latest `8.0.6` does not update `webpack-dev-middleware` dependency - https://github.com/storybookjs/storybook/blob/next/code/builders/builder-webpack5/package.json#L97

As solution - using `overrides` to specifify version above `6.1.2`

### CODE REVIEW

**Review by devinea — COMMENTED** [review]
Please also update https://github.com/SAP/open-ux-tools/blob/main/docs/version-overrides.md

**Comment by 815are** [comment]
> Please also update https://github.com/SAP/open-ux-tools/blob/main/docs/version-overrides.md

updated within commit -> https://github.com/SAP/open-ux-tools/pull/1814/commits/e4fb113429800ed2d607a8fff22ebf95499f7a68

**Review by devinea — APPROVED** [review]
package update and override  seems appropriate to fix security issue

**Review by Klaus-Keller — APPROVED** [review]
Thanks @815are! 
- version bump looks good
- version overrides is maintained

Approved from my side.

**Pull request merged**
