### PR TITLE
chore: version of pnpm, enable corepack support

### PR DESCRIPTION
**Pull request by Klaus-Keller**
# Issue
Improvements for `pnpm`.

## Description
- set `engines.pnpm` to version `8` in `package.json`
- as `pnpm@8` requires node 16, I've changed the min node version to 16.
- enable [`corepack`](https://github.com/nodejs/corepack) for developers that use multiple package managers
- use latest version `pnpm@8.5.1` for pipeline runs with GitHub actions
- updated the `pnpm-lock.yaml` using `pnpm install` in root with version `8.5.1`

### CODE REVIEW

**Review by devinea — DISMISSED** [review]
Updates look good. 1 minor suggestion.

**Comment by devinea** [comment]
FYI new pnpm version and new lockfileVersion https://github.com/pnpm/pnpm/releases/tag/v8.6.0

**Comment by Klaus-Keller** [comment]
Hi @devinea, 
- changed this PR to use `pnpm@8.6.0`
- enabled node 20 builds but revoked it again. We need to adjust `engines.node` entries in `package.json` of more than 20 modules. Let's first align on this and handle it in separate PR.

**Review by devinea — APPROVED** [review]
Thanks for the update

**Review by slin-sap — APPROVED** [review]

**Pull request merged**
