### PR TITLE
fix: Add custom page action" is not available on the Object Page of an ADP app

### PR DESCRIPTION
**Pull request by vadson71**
Fixed a bug when quick action "Add custom page action" is not available on the Object Page of an ADP app

### CODE REVIEW

**Review by nikmace — APPROVED** [review]
Code looks good
Tests adjusted, coverage is excellent
Did not test manually

**Comment by nikmace** [comment]
@vadson71 could you please update the PR title with what the fix is about, because bug fix is too generic and not descriptive enough and so other reviewers can better understand what this PR is about. thanks

**Comment by nikmace** [comment]
> > @vadson71 could you please update the PR title with what the fix is about, because bug fix is too generic and not descriptive enough and so other reviewers can better understand what this PR is about. thanks
> 
> Updated. Thanks!

I was talking about the PR title (fix: bug fix). :)

**Review by Jimmy-Joseph19 — APPROVED** [review]
Changes looks good.
Changeset found
Test coverage good.

**Pull request merged**
