### PR TITLE
fix: storybook issue after storybook update

### PR DESCRIPTION
**Pull request by 815are**
Issue after storybook version update from "7.6.18" to "8.1.11", which was done in https://github.com/SAP/open-ux-tools/pull/1995

It introduced several issues with `pnpm storybook` commands in `packages.ui-components` -> https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/package.json#L30
1. `storybook` commands fails:
image

2. vscode variables local file fails to load:;
image

3. Warning about unmatching versions of "@storybook/react",  "@storybook/react-webpack5" with "storybook":
image

4. Some themming issues based on latest storybook ui;
image

### CODE REVIEW

**Review by devinea — COMMENTED** [review]
Thanks @815are for fixing these. Can you add a changeset?

**Comment by 815are** [comment]
> Thanks @815are for fixing these. Can you add a changeset?

done -> https://github.com/SAP/open-ux-tools/pull/2180/commits/42e010e52b0968389cde23f15ded371ef2d794e7

**Review by devinea — APPROVED** [review]
Thanks @815are

**Review by broksy — DISMISSED** [review]
Understandable change and changeset.
Did not check locally.
Approved from my side.

**Review by broksy — APPROVED** [review]

**Review by devinea — APPROVED** [review]
re-approving

**Pull request merged**
