### PR TITLE
feat(ui5-writer): use @sapui5/types with UI5 1.113 and newer

### LINKED ISSUE #999: TBI - Switch to @sapui5/types with UI5 1.113 and newer
### Description (include screenshots)
Starting with release 1.113, please use the identical package `@sapui5/types` instead
https://www.npmjs.com/package/@sapui5/ts-types-esm/v/1.113.0

### Value
Best practice

### Architecture Elaboration
n/a

### Notes
n/a

### Tasks
- [ ] Change the code
- [ ] update the snapshots

### PR DESCRIPTION
**Pull request by MariusFreitag**
As described in the [@sapui5/ts-types-esm README file](https://www.npmjs.com/package/@sapui5/ts-types-esm), `@sapui5/types` should be preferred for newer SAPUI5 versions.

This closes #999.

### CODE REVIEW

**Review by Klaus-Keller — DISMISSED** [review]
Thanks @MariusFreitag,
- code enhancement for new types packages looks good and is easy to understand
- test coverage is great
- build and tested locally, no issues found

Approved from my side

**Review by devinea — COMMENTED** [review]
Thanks @MariusFreitag 
Code changes, tests and changeset look good.

I think it would be helpful to add some more tests for generated TypeScript  projects 
Copying this for example for a ui5 version 1.113.0 or higher 
https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-elements-writer/test/lrop.test.ts#L197-L214
Running the tests with `UX_DEBUG=true UX_DEBUG_FULL=true  npm test` in `packages/fiori-elements-writer/` will do additional checks in the project like (npm install and type checking )

Also here https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/test/listdetail.test.ts#L96-L129

**Comment by MariusFreitag** [comment]
> I think it would be helpful to add some more tests for generated TypeScript projects

Good point, I actually did this to test manually, but I will also commit two tests (one with V4 < 1.113 and one with V4 >= 1.113) to this PR

**Comment by MariusFreitag** [comment]
@devinea I checked the existing coverage again and added the two tests you recommended. I think they cover the scenarios quite well.

I also tried `npm install` for the generated applications, and everything worked fine.

**Review by Klaus-Keller — APPROVED** [review]
Approve again after added tests

**Review by devinea — APPROVED** [review]
@MariusFreitag Thanks for adding the extra tests. 
All looks good to me.

**Pull request merged**
