### PR TITLE
Feature Branch: File Exclusion & template updates for CAP Applications

### PR DESCRIPTION
**Pull request by kjose90**
https://github.com/SAP/open-ux-tools/issues/2031

Add `projectType` mandatory option to `App` interface to specify the type of project being processed. This option determines file inclusion/exclusion and script updates in the template:
- For projects of type 'CAPJava' or 'CAPNodejs':
  - Exclude `ui5-local.yaml` and `.gitignore` from the template.
  - Update `package.json` to include only the script `deploy-config`.
  - Use full URLs to determine resource URLs in `webapp/index.html` and `flpSandbox.html`.
- For projects of type 'EDMXBackend':
  - Include `ui5-local.yaml` and `.gitignore` in the template.
  - Update `package.json` to include the following scripts: start, start-local, build, start-noflp, start-mock, int-test, deploy, and sap-ux.
  - Include relative URLs to determine resource URLs in `webapp/index.html` and `flpSandbox.html`.
  
  Updated tests & snapshots with `projectType` under` fiori-freestyle-writer`, `fiori-elements-writer`, `ui5-application-writer` & `odata-service-writer`

### CODE REVIEW

**Comment by kjose90** [comment]
Added new option: `projectType` to App interface to determine if the project is `EDMXBackend`, `CAPJava`, or `CAPNodejs`.

- In `ui5-application-writer`, the `projectType` flag is used to exclude the` ui5-local.yaml `and .`gitignore` files from the templates for CAPJava and CAPNodejs projects.
- In `fiori-freestyle-writer,` the `ui5-local.yaml ` file is written only if the `projectType` is not CAPJava or CAPNodejs.
- Updated Tests:

Added tests to `ui5-application-writer` to ensure that `ui5-local.yaml` and `.gitignore` files are excluded for CAPNodejs projects.

- Updated `basic.test.ts` in `fiori-freestyle-writer` to verify that `ui5-local.yaml` and .`gitignore` files are not generated for CAPNodejs projects & typescript enabled.
- Updated `lrop.test.ts` in `fiori-elements-writer` to verify that `ui5-local.yaml` and `.gitignore` files are not generated for CAPNodejs projects & typescript enabled.

**Comment by heimwege** [comment]
Hey @kjose90 👋🏻 
I just stumbled across this draft PR and now I'm asking myself why there is no need for a `ui5-local.yaml` in CAPJava projects? 🤔  We're using CAPJava and every app has a `ui5-local.yaml` to start the UI independent from the CAP backend (using `@sap-ux/ui5-middleware-fe-mockserver`) e.g. for OPA5 tests. If the OPA5 tests would include the backend they would
1. be much slower (at least in case of a Java backend) and
2. rather be e2e tests than integration tests and thus be done using wdi5 (see restrictions of OPA5 [here](https://sapui5.hana.ondemand.com/sdk/#/topic/2696ab50faad458f9b4027ec2f9b884d)).

**Review by devinea — COMMENTED** [review]
Changes look good. There are additional manually run tests in FE and FF writers.
`UX_DEBUG=true UX_DEBUG_FULL=true  npm test`
Screenshot 2024-07-15 at 16 56 24

I think those tests can skip that script if it is missing for CAP.

**Comment by devinea** [comment]
> I just stumbled across this draft PR and now I'm asking myself why there is no need for a `ui5-local.yaml` in CAPJava projects? 🤔 We're using CAPJava and every app has a `ui5-local.yaml` to start the UI independent from the CAP backend (using `@sap-ux/ui5-middleware-fe-mockserver`) e.g. for OPA5 tests. If the OPA5 tests would include the backend they would
> 
> 1. be much slower (at least in case of a Java backend) and
> 2. rather be e2e tests than integration tests and thus be done using wdi5 (see restrictions of OPA5 [here](https://sapui5.hana.ondemand.com/sdk/#/topic/2696ab50faad458f9b4027ec2f9b884d)).

@heimwege I assume in your project you are using the mockserver with edmx(xml) files to run the tests?
By default we prefer not to mix cds and edmx formats in the project source. 
I think in future it could make sense to start the mockserver from cds source files, but this isn't fully supported currently.

**Comment by heimwege** [comment]
> > I just stumbled across this draft PR and now I'm asking myself why there is no need for a `ui5-local.yaml` in CAPJava projects? 🤔 We're using CAPJava and every app has a `ui5-local.yaml` to start the UI independent from the CAP backend (using `@sap-ux/ui5-middleware-fe-mockserver`) e.g. for OPA5 tests. If the OPA5 tests would include the backend they would
> > 
> > 1. be much slower (at least in case of a Java backend) and
> > 2. rather be e2e tests than integration tests and thus be done using wdi5 (see restrictions of OPA5 [here](https://sapui5.hana.ondemand.com/sdk/#/topic/2696ab50faad458f9b4027ec2f9b884d)).
> 
> @heimwege I assume in your project you are using the mockserver with edmx(xml) files to run the tests? By default we prefer not to mix cds and edmx formats in the project source. I think in future it could make sense to start the mockserver from cds source files, but this isn't fully supported currently.

@devinea You are absolutely right about the setup of our project. Thanks for the explanation. If I find some time I'll have a look at [@sap-ux/fe-mockserver-plugin-cds](https://www.npmjs.com/package/@sap-ux/fe-mockserver-plugin-cds) 🐱

**Comment by kjose90** [comment]
> Changes look good. There are additional manually run tests in FE and FF writers. `UX_DEBUG=true UX_DEBUG_FULL=true npm test` Screenshot 2024-07-15 at 16 56 24
> 
> I think those tests can skip that script if it is missing for CAP.

Thanks Austin - I have added a check to ignore checking those scripts if project is CAP

**Review by devinea — APPROVED** [review]
Code changes look great. 
Covered by tests and expected output looks good. 
Changeset ✅

**Review by IainSAP — APPROVED** [review]
Thanks @kjose90 

- All contributing PRs already reviewed  (on feature branch)
- No additional review needed to approving

**Pull request merged**
