### PR TITLE
Fix - The mark for saved/unsaved change not updated on Save/Delete change

### PR DESCRIPTION
**Pull request by Dannysht**
Fix for #1618 

Mark now changes momentarily on saved changes

### CODE REVIEW

**Review by nikmace — APPROVED** [review]
Small and easy-to-understand change
Coverage not applicable

**Review by voicis — APPROVED** [review]
- small and easy to understand change
- coverage not affected
- tests passing
- manually tested

**Comment by zdravko-georgiev** [comment]
@Dannysht @nikmace This PR is missing the changeset for the `preview-middleware` in order to be consumed.

**Comment by nikmace** [comment]
> @Dannysht @nikmace This PR is missing the changeset for the `preview-middleware` to be consumed.

Does the PR need to be reverted and the changeset changes to be added?

**Comment by zdravko-georgiev** [comment]
> > @Dannysht @nikmace This PR is missing the changeset for the `preview-middleware` to be consumed.
> 
> Does the PR need to be reverted and the changeset changes to be added?

No, if it is not urgent it will be done with the next change, e.g. https://github.com/SAP/open-ux-tools/pull/1597.

**Comment by voicis** [comment]
There is also #1569 which could be merged soon.

**Pull request merged**
