### PR TITLE
feat(axios-extension): Add PATH to debug output

### PR DESCRIPTION
**Pull request by gregorwolf**
Hello Open UX Tools,

during the Fiori Training I've delivered last week I came across the issue that I ran the deploy to an ABAP Backend but it failed with with an error. Setting `log: 4` did only provide this additional information:

```
Retrieving application ZEXCEL_DU, AxiosError: Request failed with status code 403
```

Only because I've developed the backend service using ABAP in Eclipse I've noticed the following error in the Feed Reader:

image

with this details:

image

After activating the service in transaction /IWFND/MAINT_SERVICE the issue is gone. But I think this should be made easier by adding information which PATH is called in the ABAP backend to the debug output. It might be even better if the PATH is already shown in the error.

Best Regards
Gregor

### CODE REVIEW

**Comment by longieirl** [comment]
Typically this is the GA page we provide when a HTTP 403 is returend;

https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:45996:50742:46000

Once the prerequisites are met, it resolves most problems.

**Review by longieirl — APPROVED** [review]
Code changes look good.
Not sure how this will help other ABAP developers? In the sense, they will know to enable the appropiate transaction.

**Comment by gregorwolf** [comment]
As filed in #1897 this Guided Answer isn't clickable. Also the client app should provide detail information at least in debug mode to help the user directly.

**Comment by devinea** [comment]
@gregorwolf Thanks for your contribution. 
I've copied your commits onto a branch on https://github.com/SAP/open-ux-tools so that the build pipeline runs fully.
https://github.com/SAP/open-ux-tools/pull/1915

**Pull request closed without merging**
