### PR TITLE
update(freestyle): update eslint.rc to ignore dist folder after deployment

### PR DESCRIPTION
**Pull request by ciaradaly2021**
## Issue Description

Issue #213 

relevant to issue in App Gen where eslint doesn't cover deployed app dist folder and throws errors. This has since been rectified for Fiori-elements but is still presenting issues for fiori freestyle, as shown:

ff_issue

## Checklist for Pull Requests

- [x] Supplied as many details as possible on this change.
- [x] The code conforms to the general [development principles](https://github.wdf.sap.corp/ux-engineering/tools-suite/tree/master/docs/dev-guide).
- [x] This branch is appropriately named for the associated issue.

### CODE REVIEW

**Review by tobiasqueck — APPROVED** [review]
Thanks for catching this one!

**Review by IainSAP — APPROVED** [review]

**Review by devinea — APPROVED** [review]

**Review by devinea — COMMENTED** [review]
@ciaradaly2021 - would be best to run `pnpm cset` to create a patch release so that a new version is released after merge to main. And update snapshots for failing tests

**Comment by theStiggySpd** [comment]
Hi @ciaradaly2021 thanks for the fix. 
Can you please also create an issue https://github.com/SAP/open-ux-tools/issues/new/choose and link it to this pr

**Comment by ciaradaly2021** [comment]
> Hi @ciaradaly2021 thanks for the fix. Can you please also create an issue https://github.com/SAP/open-ux-tools/issues/new/choose and link it to this pr

Issue created: https://github.com/SAP/open-ux-tools/issues/213. 
> @ciaradaly2021 - would be best to run `pnpm cset` to create a patch release so that a new version is released after merge to main. And update snapshots for failing tests

I made this change on github as it is small, I don't have this repo locally but if needed I can. I won't be available again until Thursday so if this needs to be changed asap it will likely have to be performed by someone else, if not I can do on Thurs. Thanks.

**Comment by devinea** [comment]
Replaced by https://github.com/SAP/open-ux-tools/pull/227 closing. Thanks @ciaradaly2021

**Pull request closed without merging**
