### PR TITLE
fix(ui5-application-inquirer): Wrong arg order

### PR DESCRIPTION
**Pull request by IainSAP**
#1724

- Fixes wrong arg ordering when internally calling `getPrompts(...)`
- Removes in-line `exports` which was only added to support test mocking
- Removes unnecessary clone, remnant of previous implementation when prompt options were cleaned
- Add test to cover

### CODE REVIEW

**Review by cianmSAP — DISMISSED** [review]
Code changes look good
Covered in tests
Patch changeset ✅

**Review by devinea — DISMISSED** [review]

**Review by tobiasqueck — APPROVED** [review]
* changeset ok
* fix ok - sorry for missing it in the previous PRs review

**Review by cianmSAP — APPROVED** [review]
Re-approval

**Review by longieirl — APPROVED** [review]
Changes look good.
Test coverage is good.

**Pull request merged**
