### PR TITLE
chore(uie): replace vscuie prefix in css vars with vscode

### PR DESCRIPTION
**Pull request by tom-sap**
Cleanup, as requested by design team.

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
@tom-sap, what about the style var definitions in https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/styles/_color.scss? Can they be removed? @815are can you confirm?

**Comment by tom-sap** [comment]
@Klaus-Keller thanks for that. I'm pretty sure that this file is not used anymore (and hasn't been for a while now).
Will ask guys to confirm.

**Comment by 815are** [comment]
> @tom-sap, what about the style var definitions in https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/styles/_color.scss? Can they be removed? @815are can you confirm?

@Klaus-Keller 
I think idea is to remove it. But we still use those variables in out extensions - so we will need adapt(replace vscuie) in our webview extension code as well. If we will run extension webview code against latest `ui-components` - there would be ui issues

**Review by 815are — DISMISSED** [review]
looks ok - did not find any reference to `vscuie`
Tested with storybook - did not notice issues

**Review by 815are — APPROVED** [review]

**Comment by Klaus-Keller** [comment]
> @Klaus-Keller I think idea is to remove it. But we still use those variables in out extensions - so we will need adapt(replace vscuie) in our webview extension code as well. If we will run extension webview code against latest `ui-components` - there would be ui issues

Thanks for looking into this @815are. I'll create a follow up ticket to cleanup.

**Pull request merged**
