### PR TITLE
fix sonar issue

### PR DESCRIPTION
**Pull request by slin-sap**
Fix sonar issue about Array.reduce() call missing default value.

Link to original sonar issue:
https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER,CRITICAL,MAJOR,MINOR&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AY6jPjnTed7kdlBgm2p4&tab=code

### CODE REVIEW

**Review by kranthie-sap — APPROVED** [review]
* The code changes look good

**Review by longieirl — COMMENTED** [review]
Do we need a test for this?

**Comment by slin-sap** [comment]
> Do we need a test for this?

Good question. I ran unit tests locally and checked test coverage. This function is already covered by unit tests and being triggered 16 times. I am not sure why test is not triggered in this PR.

**Review by longieirl — APPROVED** [review]
Thanks @slin-sap 
Changes look good.

**Pull request merged**
