### PR TITLE
chore: define code owners for the middlewares

### PR DESCRIPTION
**Pull request by zdravko-georgiev**
Defines code owners for the `ui5-proxy-middleware` and the `backend-proxy-middleware`.

### CODE REVIEW

**Comment by zdravko-georgiev** [comment]
@tobiasqueck @ullasholla @Klaus-Keller I am proposing you as code owners for middlewares. If you have any objections please _speak now of forever hold your peace_ 😉

**Comment by zdravko-georgiev** [comment]
@donal-tobin-sap Could you please add the 2 teams `@SAP/ux-tools-ui5-proxy-middleware` and `@SAP/ux-tools-backend-proxy-middleware` to the `open-ux-tools` repository?

**Review by Klaus-Keller — DISMISSED** [review]
Team assignments for ui5-proxy-middleware and ui5-backend-middleware looks good, thanks @zdravko-georgiev.

**Review by tobiasqueck — APPROVED** [review]

**Review by Klaus-Keller — APPROVED** [review]
Assignment of code owners looks good.

**Comment by Klaus-Keller** [comment]
@zdravko-georgiev, all green, I merge this now.

**Comment by zdravko-georgiev** [comment]
Thanks @Klaus-Keller!

**Pull request merged**
