### PR TITLE
feat: app info file handling logic to new module @sap-ux/fiori-tools-settings

### PR DESCRIPTION
**Pull request by kjose90**
Create new module `@sap-ux/fiori-tools-settings`
- Introduced functionality to handle `appInfo.json` within the `.fioritools` folder where a file path of currently generated app will be written.
- Implemented `writeApplicationInfoSettings` to store the latest generated app's file path.
- Added `loadApplicationInfoFromSettings` to read and load the application info from the stored latest generated app's file path.
- Enabled deletion of the `appInfo.json` file via `deleteAppInfoSettings` to ensure proper cleanup.
- Unit tests.

### CODE REVIEW

**Review by devinea — DISMISSED** [review]
New module setup, implementation and test looks good. 
We should move get fioritools folder path and consts from project-access and store and export from here in another PR.
Changset ✅

**Review by cianmSAP — APPROVED** [review]
New module looks good
- Functions are clear and well doc'd
- Tests to cover
✅

**Review by cianmSAP — APPROVED** [review]
Re-approving

**Review by devinea — APPROVED** [review]
Re-approving

**Pull request merged**
