### PR TITLE
Chore - fix audit issues and chore upgrades

### PR DESCRIPTION
**Pull request by devinea**

### CODE REVIEW

**Comment by zdravko-georgiev** [comment]
@devinea Would it possible to fix the issues reported by sonar?

**Comment by devinea** [comment]
> @devinea Would it possible to fix the issues reported by sonar?

@zdravko-georgiev Done. thanks

**Review by zdravko-georgiev — APPROVED** [review]
Version updates of `nock` and `ui5/cli` packages looks good
Review comments addressed
Version override documented

**Comment by zdravko-georgiev** [comment]
> > @devinea Would it possible to fix the issues reported by sonar?
> 
> @zdravko-georgiev Done. thanks

Thanks @devinea

**Pull request merged**
