### PR TITLE
fix(locate-reuse-lib): corrected extraction of component name

### PR DESCRIPTION
**Pull request by devinea**
Changes from https://github.com/SAP/open-ux-tools/pull/2071. Thanks @paraggarg89

"sap.ui5"/"componentUsages" contains object map having "name" property where component name is specified. 
e.g. 
```JSON
{
...
 componentUsages: {
            "componentUsage1": {
                "name": "sap.nw.core.applogs.lib.reuse.smarttemplate",
                "lazy": true
            }, 
            "componentUsage2": {
                "name": "sap.s4.cfnd.bpf.lib.reuse.component.smarttemplate",
                "lazy": true
            }
 }
...
}
```
So instead of key of componentUsages object, logic should extract component name from "name" property inside the object.

- call createRender using async
https://github.com/SAP/open-ux-tools/issues/969#issuecomment-2211065454

### CODE REVIEW

**Review by tobiasqueck — CHANGES_REQUESTED** [review]
Please make sure that the same also works in the preview middleware. I think it should be here: https://github.com/SAP/open-ux-tools/blob/main/packages/preview-middleware-client/src/flp/init.ts#L93

**Comment by devinea** [comment]
> Please make sure that the same also works in the preview middleware. I think it should be here: https://github.com/SAP/open-ux-tools/blob/main/packages/preview-middleware-client/src/flp/init.ts#L93

@tobiasqueck  Done. Please re-review. 
Also updated createRender to be async like in init.ts

**Comment by devinea** [comment]
@tobiasqueck Please re-review.

**Review by tobiasqueck — APPROVED** [review]
* reviewed only the `preview-middleware-client`
* code is clear and easy to understand
* functionality is properly tested
* changeset ok
* did not test locally

**Review by kjose90 — APPROVED** [review]
Code looks good and clear
Changeset ✅

**Pull request merged**
