### PR TITLE
feat(project-access): detect `.library` libraries

### PR DESCRIPTION
**Pull request by johannes-kolbe**
https://github.com/SAP/open-ux-tools/issues/1547

detects libraries without manifest.json, but with `.library` ~~or `ui5.yaml`~~

### CODE REVIEW

**Comment by johannes-kolbe** [comment]
After discussion with @Klaus-Keller, expectation of libraries is that they have at least either a `manifest.json` or a `.library` file.

**Review by Klaus-Keller — APPROVED** [review]
Thanks @johannes-kolbe!
- addition to find libraries without `manifest.json`
- test coverage is good
- did a visual review, no local test

Approved from my side

**Review by zdravko-georgiev — APPROVED** [review]
Code looks good
Very good test coverage
Did NOT tested manually

**Comment by johannes-kolbe** [comment]
Thanks @Klaus-Keller, @zdravko-georgiev!

**Pull request merged**
