### PR TITLE
Revert "feat(fiori-elements-writer): remove `sap.fe.templates` depend…

### PR DESCRIPTION
**Pull request by martinjanus-sap**
This reverts commit 9188fe8bf9adb50e9265dc559453807b3e617ac7.

Introduction of this should be reverted, AppM side to be updated first.

### CODE REVIEW

**Review by devinea — APPROVED** [review]
Temporary revert looks good. Thanks @martinjanus-sap

**Review by devinea — APPROVED** [review]
re-approving

**Review by Klaus-Keller — APPROVED** [review]
revert approved.

**Comment by devinea** [comment]
linking to https://github.com/SAP/open-ux-tools/issues/1942

**Pull request merged**
