### PR TITLE
fix: outline tree for Fiori applications is not collapsed correctly

### PR DESCRIPTION
**Pull request by nikmace**
Fix for #1435.

- Sets the `isAllGroupsCollapsed` state for all groups initially for `UIList`.
- Adds translation for extension point tooltip text.

### CODE REVIEW

**Review by zdravko-georgiev — CHANGES_REQUESTED** [review]
Please add also a `patch` for the `preview-middleware`

**Comment by nikmace** [comment]
> 85db9a5

Patch added: [85db9a5](https://github.com/SAP/open-ux-tools/pull/1436/commits/85db9a5554f5d5b479058e6b9d558ec6fcf4f6bc)

**Comment by nikmace** [comment]
> Please add also a `patch` for the `preview-middleware`

Patch added: [85db9a5](https://github.com/SAP/open-ux-tools/pull/1436/commits/85db9a5554f5d5b479058e6b9d558ec6fcf4f6bc)

**Review by zdravko-georgiev — APPROVED** [review]
Code is simple and easy to understand
Excellent test coverage
Changeset is OK
Did NOT tested manually

**Review by voicis — APPROVED** [review]

**Pull request merged**
