### PR TITLE
chore(axios-ext): reset version to 0.15.1

### PR DESCRIPTION
**Pull request by kranthie-sap**
## Description
* Reset `axios-extension` package version to `0.15.1`

## Type of change
- [ ] Bug (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a new feature)
- [ ] Breaking change (Bug or New feature that would cause existing functionality/consumers to not work as expected)
- [x] Non-Breaking chores (Changes to tools, libraries, build process, documentation, etc)
- [ ] None of the above (Reviewers might ask for more clarification)

## How have you tested?
Make it easier for reviewer by describing the tests you have done to verify your changes and provide clear instructions for reviewers to reproduce.

## Checklist:
- [x] The code conforms to the [general development principles](https://github.com/SAP/open-ux-tools/blob/main/docs/Guidelines.md)
- [x] Supplied as many details as possible on this change
- [x] The code is easy to read and maintainable by others
- [ ] Corresponding changes to the documentation has been done
- [ ] Already existing and new unit tests pass locally

### CODE REVIEW

**Review by ullasholla — APPROVED** [review]
Changes look good, thanks @kranthie-sap

**Review by slin-sap — APPROVED** [review]

**Comment by devinea** [comment]
1.0.0 is already published. Do you plan to delete it from the registry?
Is it worth reverting?

**Comment by kranthie-sap** [comment]
@devinea: I tried deleting the `1.0.0` version, but it looks like `npm unpublish` fails if there are already dependents on npmjs (not necessarily for the same version). I unpublished `@sap-ux/backend-proxy-middleware@0.6.41` and `@sap-ux/environment-check@0.15.3`, but the unpublish for `@sap-ux/axios-extension@1.0.0` fails. I am waiting for feedback from npmjs on the issue.

**Comment by tobiasqueck** [comment]
That one is obsolete, correct?

**Comment by kranthie-sap** [comment]
Yes, it looks like the only solution is to deprecate the `1.0.x` versions which is probably not desirable. I'll close the PR.

**Pull request closed without merging**
