### PR TITLE
Fix/1116/support cli credentials

### PR DESCRIPTION
**Pull request by longieirl**
Fix for https://github.com/SAP/open-ux-tools/issues/1116

- appended unit tests
- supports username | password as a CLI param which conflicts with other existing CLI params
- supports dotenv files
- Re-using the `process.env.SERVICE_USERNAME` name since this values is also used for cloud service env flow soo just being consistent
- Re-using `--username` since this is the same property name used if reading from a yaml configuration, as shown below

Existing/as-is flow supporting dotenv and yaml configuration
```
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        verbose: true
        target:
          url: https://myapabap-system.sap:44300
        credentials:
          username: env:XYZ_USER
          password: env:XYZ_PASSWORD
        app:
          name: ZTRAJL2403
          description: Test
          package: $tmp
          transport: Y12345
```
Existing deploy command;
```
./bin/undeploy -c ./ui5-deploy.yaml
```
dotnev file;
```
XYZ_USER=TESTNEW
XYZ_PASSWORD=TESTNEW
```

With the latest changes, to support the same flow using CLI params and no yaml configuration and re-using the same dotenv file as above;
```
./bin/undeploy --url https://myapabap-system.sap:44300 --name ZTRAJL2403 --description Test --package '$tmp' --transport Y12345 --username env:XYZ_USER --password env:XYZ_PASSWORD --verbose
```

Supporting dotenv file without username | password CLI params;

```
./bin/undeploy --url https://myapabap-system.sap:44300 --name ZTRAJL2403 --description Test --package '$tmp' --transport Y12345 --verbose
```
dotenv file is
```
SERVICE_USERNAME=TESTNEW
SERVICE_PASSWORD=TESTNEW
```

### CODE REVIEW

**Review by Klaus-Keller — CHANGES_REQUESTED** [review]
Hi @longieirl, 
Could you please have a look at the [6 code smells ](https://sonarcloud.io/project/issues?id=SAP_open-ux-tools&pullRequest=1117&resolved=false&types=CODE_SMELL)found by Sonar?

**Comment by longieirl** [comment]
> Hi @longieirl, Could you please have a look at the [6 code smells ](https://sonarcloud.io/project/issues?id=SAP_open-ux-tools&pullRequest=1117&resolved=false&types=CODE_SMELL)found by Sonar?

Thank you for that! Didnt notice that at all.

**Review by Klaus-Keller — APPROVED** [review]

**Review by Klaus-Keller — APPROVED** [review]
Thanks @longieirl!

- code changes look good
- test coverage is great
- did not locally test

Approved from my side.

**Review by slin-sap — APPROVED** [review]
Didn't test locally. 

- code changes look good
- new options are added to the README documentation
- minor version bump is justified since there is new input option added

**Pull request merged**
