### PR TITLE
fix(odata-service-writer): #580 prevents oDataService properties being used as ejs render options

### PR DESCRIPTION
**Pull request by IainSAP**
Fixes: https://github.com/SAP/open-ux-tools/issues/580

By passing an empty options object into `ejs.render()` we can avoid the `oDataService` properties being interpreted as options.  

Note: This is preferable than renaming properties on a case by case basis.

### CODE REVIEW

**Review by devinea — DISMISSED** [review]

**Comment by ullasholla** [comment]
Good catch! That's very annoying on `ejs`'s part. So any of these properties in the data being passed will be interpreted as an option:
`delimiter`, `scope`, `context`, `debug`, `compileDebug`, `client`, `_with`, `rmWhitespace`, `strict`, `filename`, `async`

We still have a lot of places where this can silently break:
```
packages/ui5-application-writer/src/index.ts
73:                        const add = JSON.parse(render(fs?.read(optTmplFilePath), ui5App));

packages/fe-fpm-writer/src/column/index.ts
89:    const filledTemplate = render(fs.read(join(manifestRoot, `manifest.json`)), completeColumn);

packages/fe-fpm-writer/src/view/index.ts
78:    const filledTemplate = render(fs.read(join(root, 'view', `manifest.json`)), completeView);

packages/fe-fpm-writer/src/page/list.ts
61:        JSON.parse(render(fs.read(join(__dirname, '../../templates/page/list/manifest.json')), config)),

packages/fe-fpm-writer/src/building-block/index.ts
102:    const templateContent = render(fs.read(templateFilePath), {

packages/fe-fpm-writer/src/action/index.ts
96:    Object.assign(actions, JSON.parse(render(fs.read(join(root, `action/manifest.action.json`)), config)));

packages/fe-fpm-writer/src/section/index.ts
84:    const filledTemplate = render(fs.read(join(manifestRoot, `manifest.json`)), completeSection);

packages/fe-fpm-writer/src/page/custom.ts
78:        JSON.parse(render(fs.read(join(root, `manifest.json`)), config)),

packages/fe-fpm-writer/src/page/object.ts
52:        JSON.parse(render(fs.read(join(__dirname, '../../templates/page/object/manifest.json')), config)),

packages/fiori-elements-writer/src/index.ts
64:        JSON.parse(render(fs.read(join(rootTemplatesPath, 'common', 'extend', 'package.json')), feApp))

packages/fiori-elements-writer/src/data/manifestSettings.ts
58:            fs.extendJSON(manifestPath, JSON.parse(render(fs.read(manifestTemplatePath), templateSettings)));

47:    fs.extendJSON(manifestPath, JSON.parse(render(fs.read(join(extRoot, 'manifest.json')), ffApp)));
52:        render(fs.read(join(extRoot, 'i18n', 'i18n.properties')), ffApp)
57:    fs.extendJSON(packagePath, JSON.parse(render(fs.read(join(tmplPath, 'common', 'extend', 'package.json')), ffApp)));
```

It makes sense to fix all these places (future enhancements to the interfaces will introduce bugs).

How shall we go about fixing these?

**Comment by IainSAP** [comment]
> Good catch! That's very annoying on `ejs`'s part. So any of these properties in the data being passed will be interpreted as an option: `delimiter`, `scope`, `context`, `debug`, `compileDebug`, `client`, `_with`, `rmWhitespace`, `strict`, `filename`, `async`
> 
> We still have a lot of places where this can silently break:
> 
> ```
> packages/ui5-application-writer/src/index.ts
> 73:                        const add = JSON.parse(render(fs?.read(optTmplFilePath), ui5App));
> 
> packages/fe-fpm-writer/src/column/index.ts
> 89:    const filledTemplate = render(fs.read(join(manifestRoot, `manifest.json`)), completeColumn);
> 
> packages/fe-fpm-writer/src/view/index.ts
> 78:    const filledTemplate = render(fs.read(join(root, 'view', `manifest.json`)), completeView);
> 
> packages/fe-fpm-writer/src/page/list.ts
> 61:        JSON.parse(render(fs.read(join(__dirname, '../../templates/page/list/manifest.json')), config)),
> 
> packages/fe-fpm-writer/src/building-block/index.ts
> 102:    const templateContent = render(fs.read(templateFilePath), {
> 
> packages/fe-fpm-writer/src/action/index.ts
> 96:    Object.assign(actions, JSON.parse(render(fs.read(join(root, `action/manifest.action.json`)), config)));
> 
> packages/fe-fpm-writer/src/section/index.ts
> 84:    const filledTemplate = render(fs.read(join(manifestRoot, `manifest.json`)), completeSection);
> 
> packages/fe-fpm-writer/src/page/custom.ts
> 78:        JSON.parse(render(fs.read(join(root, `manifest.json`)), config)),
> 
> packages/fe-fpm-writer/src/page/object.ts
> 52:        JSON.parse(render(fs.read(join(__dirname, '../../templates/page/object/manifest.json')), config)),
> 
> packages/fiori-elements-writer/src/index.ts
> 64:        JSON.parse(render(fs.read(join(rootTemplatesPath, 'common', 'extend', 'package.json')), feApp))
> 
> packages/fiori-elements-writer/src/data/manifestSettings.ts
> 58:            fs.extendJSON(manifestPath, JSON.parse(render(fs.read(manifestTemplatePath), templateSettings)));
> 
> 47:    fs.extendJSON(manifestPath, JSON.parse(render(fs.read(join(extRoot, 'manifest.json')), ffApp)));
> 52:        render(fs.read(join(extRoot, 'i18n', 'i18n.properties')), ffApp)
> 57:    fs.extendJSON(packagePath, JSON.parse(render(fs.read(join(tmplPath, 'common', 'extend', 'package.json')), ffApp)));
> ```
> 
> It makes sense to fix all these places (future enhancements to the interfaces will introduce bugs).
> 
> How shall we go about fixing these

We only really need to fix where there is matching properties, and this is the only one I found so far. (`OdataClient.client`). 
Do you think we need to apply this everywhere?

**Review by devinea — APPROVED** [review]
Thanks @IainSAP changes look good

**Review by ullasholla — APPROVED** [review]
Thanks @IainSAP, looks good to me

**Review by devinea — APPROVED** [review]

**Pull request merged**
