### PR TITLE
fix: missing unique react key

### PR DESCRIPTION
**Pull request by 815are**
fix to avoid react warning about unique react key:
image

scenario:
1. open storybook
2. open -> http://localhost:64403/?path=/story/tables-uitable--read-only-table

Problem - see warning in console

### CODE REVIEW

**Review by Klaus-Keller — DISMISSED** [review]
Thanks @815are,
- changes to add unique key for react control looks good
- changeset exists
- test exists
- did no manual test, just visual review

approved from my side

**Review by voicis — APPROVED** [review]
- changes looks good
- changeset exists
- missing key errors no longer appear in CPE tests

**Review by Klaus-Keller — APPROVED** [review]
Thanks @815are!
- adding unique id for items looks good
- change set exists
- test coverage is good
- did not test manually, just visual review

Approved from my side.

**Review by Klaus-Keller — APPROVED** [review]
re-approving

**Pull request merged**
