### PR TITLE
Update Icons.tsx

### PR DESCRIPTION
**Pull request by aislingnoone**
Update to info icon - icon made bigger

### CODE REVIEW

**Review by devinea — DISMISSED** [review]
Thanks @aislingnoone 
Changes look good
There is no change set in the pr so release won’t be immediate. @gpeuc mentioned this is ok

**Review by tom-sap — DISMISSED** [review]

**Review by 815are — DISMISSED** [review]

**Review by tobiasqueck — CHANGES_REQUESTED** [review]
Changeset is missing

**Comment by gpeuc** [comment]
@devinea @tobiasqueck So, we don't really have any idea what changeset is. If I go to that "Learn what changeset is" link, it basically starts with

`Run the command line script npx changeset or yarn changeset.`

and this is where you lost us. Especially because we are not doing these changes through any local tools, rather, we are doing all this through GitHub code editor directly here. So it's rather pointless to do command line stuff, when our changes are directly in the browser.

Is there a way for us to do these things using just GitHub.com as a tool?

**Comment by tobiasqueck** [comment]
> Is there a way for us to do these things using just GitHub.com as a tool?

@gpeuc  Yes, just click on `Click here if you're a maintainer who wants to add a changeset to this PR` and then update the ext in line 5++. Whatever you type there will be the text added to the changelog.

**Review by devinea — APPROVED** [review]
Thanks @aislingnoone

**Review by gpeuc — APPROVED** [review]

**Pull request merged**
