### PR TITLE
Make backend-proxy-middleware more robust

### PR DESCRIPTION
**Pull request by tobiasqueck**
* Make backend-proxy-middleware more robust by catching store errors and continuing the flow.
* improve unit tests by using a mocked store instead of the real one

The issue was found when running the `backend-proxy-middleware` unit tests on a machine that had matching but invalid entries in the secure store

### CODE REVIEW

**Comment by zdravko-georgiev** [comment]
@tobiasqueck If I can't access the store and get the credentials, will the application then start successfully? If no, why continue the flow?

**Comment by tobiasqueck** [comment]
You don't need the store, it is only convenience. For user/password you will be prompted by the browser, and for ABAP on BTP, you will also get a form to provide a service key.

**Review by zdravko-georgiev — DISMISSED** [review]
code looks good
very good test coverage
manual test ✅

**Review by Klaus-Keller — DISMISSED** [review]
Code looks good, test coverage is great. 
Didn't build it locally, but from what I see it is basically wrapping store access in `try/catch`.
Approved!

**Comment by zdravko-georgiev** [comment]
@tobiasqueck OK to merge?

**Comment by tobiasqueck** [comment]
The internal reporter of the issue tried it but it didn't help. So, it needs some additional work.

**Review by zdravko-georgiev — APPROVED** [review]

**Review by IainSAP — APPROVED** [review]
Thx @tobiasqueck 

-  Tested locally, no longer prompted for key store access and tests now pass.

**Comment by ravish-garg** [comment]
> hen start success

Hi Tobias,
I am encountering issues with secure store unable to read the key for a Trial BTP ABAP env. 
Error:
```
Could not get hold of vscode
warn backend-proxy-middleware Dummy store. Trying to retrieve for service: fiori/v2/system, key: https://XXXXXXXXXXXX.abap.us10.hana.ondemand.com
error fiori-tools-proxy Failed to register backend for /sap. Check configuration in yaml file.
error fiori-tools-proxy         Error: Cannot connect to ABAP Environment on BTP without service keys.
```

Environment: Windows 10
All extensions are latest versions. This happens only for BTP connection. The system is connected & saved in the SAP Systems within VS Code.

**Comment by ravish-garg** [comment]
> You don't need the store, it is only convenience. For user/password you will be prompted by the browser, and for ABAP on BTP, you will also get a form to provide a service key.

Hi @tobiasqueck 
I am encountering issues with secure store unable to read the key for a Trial BTP ABAP env.
Error:

```
Could not get hold of vscode
warn backend-proxy-middleware Dummy store. Trying to retrieve for service: fiori/v2/system, key: https://XXXXXXXXXXXX.abap.us10.hana.ondemand.com
error fiori-tools-proxy Failed to register backend for /sap. Check configuration in yaml file.
error fiori-tools-proxy         Error: Cannot connect to ABAP Environment on BTP without service keys.

```
All extensions are latest versions. This happens only for BTP connection. The system is connected & saved in the SAP Systems within VS Code.
OS: Windows 10

Same thing on MacOS Monterey works flawlessly.

**Comment by tobiasqueck** [comment]
@ravish-garg could you please open this as a separate issue and we will have a look. 

Based on your error, it sounds like we are incorrectly throwing an error instead of opening a custom page to store the key. 
@ullasholla fyi

**Pull request merged**
